networks:
  internal_network:
    driver: bridge # the default
services:
  proxy:
    container_name: ${SEED_SITE_PROXY_CONTAINER_NAME:-PROXY}
    image: caddy:2.6.4
    depends_on:
      - seed-daemon
      - seed-web
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    networks:
      - internal_network
    environment:
      - "SEED_SITE_HOSTNAME=${SEED_SITE_HOSTNAME}"
      - "SEED_SITE_BACKEND_GRPCWEB_PORT=${SEED_SITE_BACKEND_GRPCWEB_PORT:-56001}"
      - "SEED_SITE_LOCAL_PORT=${SEED_SITE_LOCAL_PORT:-3000}"
    volumes:
      - ${SEED_SITE_WORKSPACE:-~/.seed-site}/proxy/data:/data
      - ${SEED_SITE_WORKSPACE:-~/.seed-site}/proxy/config:/config
      - ${SEED_SITE_WORKSPACE:-~/.seed-site}/proxy/CaddyFile:/etc/caddy/Caddyfile

  seed-web:
    container_name: seed-web
    image: seedhypermedia/gateway:${SEED_SITE_TAG:-latest}
    depends_on:
      - seed-daemon
    networks:
      - internal_network
    ports:
      - "${SEED_SITE_LOCAL_PORT:-3000}:${SEED_SITE_LOCAL_PORT:-3000}"
    restart: unless-stopped
    volumes:
      - ${SEED_SITE_WORKSPACE:-~/.seed-site}/web:/data:rw
    environment:
      - "SEED_BASE_URL=${SEED_SITE_HOSTNAME}"
      - "GRPC_HOST=http://seed-site:${SEED_SITE_BACKEND_GRPCWEB_PORT:-56001}"
      - "DATA_DIR=/data"

  seed-daemon:
    container_name: seed-daemon
    image: seedhypermedia/site:${SEED_SITE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "56000:56000"
      - "56000:56000/udp"
    networks:
      - internal_network
    environment:
      - "SENTRY_DSN=${SEED_SITE_SENTRY_DSN:-https://47c66bd7a6d64db68a59c03f2337e475@o4504088793841664.ingest.sentry.io/4505527493328896}"
    volumes:
      - ${SEED_SITE_WORKSPACE:-~/.seed-site}/daemon:/data:rw
      - ${SEED_SITE_MONITORING_WORKDIR:-./monitoring}/grafana:/exported_grafana:rw
      - ${SEED_SITE_MONITORING_WORKDIR:-./monitoring}/prometheus:/exported_prometheus:rw
    command: >
      sh -c "rsync -a /monitoring/prometheus/ /exported_prometheus &&
             rsync -a /monitoring/grafana/ /exported_grafana && 
             seed-daemon -data-dir=/data -lndhub.mainnet -p2p.port=56000 --http.port=${SEED_SITE_BACKEND_GRPCWEB_PORT:-56001} -syncing.allow-push=${SEED_SITE_ALLOW_PUSH:-false} -grpc.port=56002 -syncing.no-discovery=${SEED_SITE_NO_DISCOVERY:-true} -syncing.no-pull=${SEED_SITE_NO_PULL:-true} ${SEED_SITE_HOSTNAME}"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    profiles:
      - metrics
    depends_on:
      - seed-site
    networks:
      - internal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - prometheus-data:/prometheus
      - ${SEED_SITE_MONITORING_WORKDIR:-./monitoring}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    container_name: grafana
    depends_on:
      - prometheus
    profiles:
      - metrics
    networks:
      - internal_network
    volumes:
      - grafana-data:/var/lib/grafana
      - ${SEED_SITE_MONITORING_WORKDIR:-./monitoring}/grafana/dashboards:/etc/grafana/dashboards:ro
      - ${SEED_SITE_MONITORING_WORKDIR:-./monitoring}/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_LOG_MODE: console
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
      GF_SERVER_HTTP_PORT: ${SEED_SITE_MONITORING_PORT:-3001}
      GF_SERVER_PROTOCOL: "http"
      GF_SERVER_DOMAIN: ${SEED_SITE_DNS:-localhost:3001}
      GF_SERVER_ROOT_URL: ${SEED_SITE_HOSTNAME:-http}/.metrics
      GF_SERVER_SERVE_FROM_SUB_PATH: True

volumes:
  grafana-data: {}
  prometheus-data: {}
