version: "3.8"
networks:
  internal_network:
    driver: bridge # the default
services:
  proxy:
    container_name: ${MTT_SITE_PROXY_CONTAINER_NAME:-PROXY}
    image: caddy:2.6.4
    depends_on:
      - seed-site
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    networks:
      - internal_network
    environment:
      - "MTT_SITE_HOSTNAME=${MTT_SITE_HOSTNAME:-http://remix}"
      - "MTT_SITE_BACKEND_GRPCWEB_PORT=${MTT_SITE_BACKEND_GRPCWEB_PORT:-56001}"
      - "MTT_SITE_LOCAL_PORT=${MTT_SITE_LOCAL_PORT:-3000}"
    volumes:
      - ${MTT_SITE_WORKSPACE:-~/.mtt-site}/proxy/data:/data
      - ${MTT_SITE_WORKSPACE:-~/.mtt-site}/proxy/config:/config
      - ${MTT_SITE_WORKSPACE:-~/.mtt-site}/proxy/CaddyFile:/etc/caddy/Caddyfile

  remix:
    container_name: ${MTT_SITE_REMIX_CONTAINER_NAME:-remix}
    image: seedhypermedia/gateway:${MTT_SITE_TAG:-latest}
    depends_on:
      - seed-site
    networks:
      - internal_network
    ports:
      - "${MTT_SITE_LOCAL_PORT:-3000}:${MTT_SITE_LOCAL_PORT:-3000}"
    restart: unless-stopped
    volumes:
      - ${MTT_SITE_WORKSPACE:-~/.mtt-site}/remix:/data:rw
    environment:
      - "SEED_BASE_URL=${MTT_SITE_HOSTNAME:-http://remix}"
      - "GRPC_HOST=http://seed-site:${MTT_SITE_BACKEND_GRPCWEB_PORT:-56001}"
      - "NEXT_PUBLIC_LN_HOST=${MTT_SITE_LN_HOST:-https://ln.mintter.com}"

  seed-site:
    image: seedhypermedia/site:${MTT_SITE_TAG:-latest}
    restart: unless-stopped
    container_name: ${SEED_SITE_DAEMON_CONTAINER_NAME:-seed-site}
    ports:
      - "56000:56000"
      - "56000:56000/udp"
    networks:
      - internal_network
    environment:
      - "SENTRY_DSN=${MTT_SITE_SENTRY_DSN:-https://47c66bd7a6d64db68a59c03f2337e475@o4504088793841664.ingest.sentry.io/4505527493328896}"
    volumes:
      - ${MTT_SITE_WORKSPACE:-~/.mtt-site}/backend:/.mtt-site:rw
      - ${MTT_SITE_MONITORING_WORKDIR:-./monitoring}/grafana:/exported_grafana:rw
      - ${MTT_SITE_MONITORING_WORKDIR:-./monitoring}/prometheus:/exported_prometheus:rw
    command: >
      sh -c "rsync -a /monitoring/prometheus/ /exported_prometheus &&
             rsync -a /monitoring/grafana/ /exported_grafana && 
             seed-site -data-dir=/.mtt-site -lndhub.mainnet -p2p.port=56000 --http.port=${SEED_SITE_BACKEND_GRPCWEB_PORT:-56001} -syncing.allow-push=${SEED_SITE_ALLOW_PUSH:-false} -grpc.port=56002 -syncing.no-discovery=${SEED_SITE_NO_DISCOVERY:-true} -syncing.no-pull=${SEED_SITE_NO_PULL:-true} ${SEED_SITE_HOSTNAME:-http://remix}"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    profiles:
      - metrics
    depends_on:
      - seed-site
    networks:
      - internal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - prometheus-data:/prometheus
      - ${MTT_SITE_MONITORING_WORKDIR:-./monitoring}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    container_name: grafana
    depends_on:
      - prometheus
    profiles:
      - metrics
    networks:
      - internal_network
    volumes:
      - grafana-data:/var/lib/grafana
      - ${MTT_SITE_MONITORING_WORKDIR:-./monitoring}/grafana/dashboards:/etc/grafana/dashboards:ro
      - ${MTT_SITE_MONITORING_WORKDIR:-./monitoring}/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_LOG_MODE: console
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
      GF_SERVER_HTTP_PORT: ${MTT_SITE_MONITORING_PORT:-3001}
      GF_SERVER_PROTOCOL: "http"
      GF_SERVER_DOMAIN: ${MTT_SITE_DNS:-localhost:3001}
      GF_SERVER_ROOT_URL: ${MTT_SITE_HOSTNAME:-http://localhost}/.metrics
      GF_SERVER_SERVE_FROM_SUB_PATH: True

volumes:
  grafana-data: {}
  prometheus-data: {}
