export default {
  title: 'Deploy a Seed site on Easypanel',
  frame: 'card',
  noZoom: true,
  posterAt: 'site',
  theme: {
    accent: '#54CD85',
    background: '#F5F5F3',
  },
  beats: [
    {name: 'dashboard', noZoom: true, zoom: false, hold: 700},
    {name: 'create-project', zoom: true},
    {name: 'project-name', zoom: true},
    {name: 'project-create', zoom: true},
    {name: 'new-service', zoom: true},
    {name: 'custom', zoom: true},
    {name: 'schema', zoom: true},
    {name: 'paste', zoom: true, hold: 500},
    {name: 'create', zoom: true},
    {name: 'web', zoom: true, hold: 600},
    {name: 'environment', zoom: true},
    {name: 'secret-line', zoom: true},
    {name: 'secret', zoom: true, hold: 500},
    {name: 'save', zoom: true},
    {name: 'deploy', zoom: true},
    {name: 'overview', zoom: true},
    {name: 'wait', noZoom: true, zoom: false, speed: true},
    {name: 'running', zoom: true, hold: 600},
    {name: 'domains', zoom: true},
    {name: 'updater', zoom: true},
    {name: 'site', zoom: true, hold: 900},
  ],
}
