export default {
  title: 'Deploy a Seed site on Dokploy',
  frame: 'card',
  noZoom: true,
  posterAt: 'site',
  theme: {
    accent: '#54CD85',
    background: '#F5F5F3',
  },
  beats: [
    {name: 'project', noZoom: true, zoom: false, hold: 700},
    {name: 'create-service', zoom: true},
    {name: 'import-option', zoom: true},
    {name: 'name', zoom: true},
    {name: 'paste', zoom: true, hold: 500},
    {name: 'load', zoom: true},
    {name: 'import', zoom: true},
    {name: 'open-service', zoom: true},
    {name: 'domains', zoom: true},
    {name: 'web-domain', zoom: true},
    {name: 'web-host', zoom: true},
    {name: 'web-cert-menu', zoom: true},
    {name: 'web-cert', zoom: true},
    {name: 'web-update', zoom: true},
    {name: 'daemon-domain', zoom: true},
    {name: 'daemon-host', zoom: true},
    {name: 'daemon-cert-menu', zoom: true},
    {name: 'daemon-cert', zoom: true},
    {name: 'daemon-update', zoom: true},
    {name: 'environment', zoom: true},
    {name: 'reveal', zoom: true, capPos: 'top'},
    {name: 'env-domain', zoom: true},
    {name: 'env-base-url', zoom: true},
    {name: 'env-save', zoom: true},
    {name: 'general', zoom: true},
    {name: 'deploy', zoom: true},
    {name: 'deploy-confirm', zoom: true},
    {name: 'wait', zoom: true, speed: true},
    {name: 'running', noZoom: true, zoom: false},
    {name: 'site', zoom: true, hold: 900},
  ],
}
