export default {
  title: 'Install a Seed site on CasaOS',
  frame: 'card',
  noZoom: true,
  posterAt: 'site',
  theme: {
    accent: '#54CD85',
    background: '#F5F5F3',
  },
  beats: [
    {name: 'dashboard', noZoom: true, zoom: false, hold: 700},
    {name: 'app-store', zoom: true},
    {name: 'sources', zoom: true},
    {name: 'more-apps', zoom: true},
    {name: 'source-url', zoom: true, hold: 500},
    {name: 'add-source', zoom: true},
    {name: 'search', zoom: true},
    {name: 'app-detail', zoom: true},
    {name: 'install', zoom: true},
    {name: 'installing', noZoom: true, zoom: false, speed: true},
    {name: 'installed', zoom: true},
    {name: 'tile-menu', zoom: true},
    {name: 'settings', zoom: true},
    {name: 'web-tab', zoom: true},
    {name: 'open-logs', zoom: true},
    {name: 'logs-tab', zoom: true},
    {name: 'registration-link', zoom: true, capPos: 'top', hold: 900},
    {name: 'close-logs', zoom: true},
    {name: 'base-url', zoom: true},
    {name: 'asset-host', zoom: true, hold: 500},
    {name: 'init-tab', zoom: true},
    {name: 'restart-policy', zoom: true, hold: 700},
    {name: 'save', zoom: true},
    {name: 'restarting', noZoom: true, zoom: false, speed: true},
    {name: 'site', zoom: true, hold: 900},
  ],
}
