export default {
  title: 'Deploy a Seed site on Coolify',
  frame: 'card',
  noZoom: true,
  posterAt: 'site',
  theme: {
    accent: '#54CD85',
    background: '#F5F5F3',
  },
  beats: [
    {name: 'project', noZoom: true, zoom: false, hold: 700},
    {name: 'new-resource', zoom: true},
    {name: 'docker-compose', zoom: true},
    {name: 'paste', zoom: true, hold: 500},
    {name: 'create', zoom: true},
    {name: 'services', zoom: true},
    {name: 'domain', zoom: true},
    {name: 'domain-edit', zoom: true},
    {name: 'protocol-menu', zoom: true},
    {name: 'protocol-https', zoom: true},
    {name: 'domain-name', zoom: true},
    {name: 'save', zoom: true},
    {name: 'confirm-port', zoom: true},
    {name: 'deploy', zoom: true},
    {name: 'wait', zoom: true, speed: true},
    {name: 'close-logs', zoom: true},
    {name: 'running', noZoom: true, zoom: false},
    {name: 'secret', zoom: true, capPos: 'top'},
    {name: 'copy-secret', zoom: true},
    {name: 'updater-resource', zoom: true},
    {name: 'updater-compose', zoom: true},
    {name: 'updater-paste', zoom: true},
    {name: 'updater-create', zoom: true},
    {name: 'updater-deploy', zoom: true},
    {name: 'updater-running', zoom: true, speed: true},
    {name: 'updater-close-logs', zoom: true},
    {name: 'site', zoom: true, hold: 900},
  ],
}
