export default {
  title: 'Deploy a Seed site on CapRover',
  frame: 'card',
  noZoom: true,
  posterAt: 'site',
  theme: {
    accent: '#54CD85',
    background: '#F5F5F3',
  },
  beats: [
    {name: 'apps', noZoom: true, zoom: false, hold: 700},
    {name: 'one-click', zoom: true},
    {name: 'search', zoom: true},
    {name: 'template', zoom: true},
    {name: 'paste', zoom: true, hold: 500},
    {name: 'next', zoom: true},
    {name: 'app-name', zoom: true},
    {name: 'domain', zoom: true},
    {name: 'secret', zoom: true},
    {name: 'deploy', zoom: true},
    {name: 'wait', zoom: true, speed: true},
    {name: 'instructions', zoom: true},
    {name: 'finish', zoom: true},
    {name: 'apps-list', zoom: true},
    {name: 'open-app', zoom: true},
    {name: 'enable-https', zoom: true},
    {name: 'force-https', zoom: true, capPos: 'top'},
    {name: 'save', zoom: true, capPos: 'top'},
    {name: 'site', zoom: true, hold: 900},
  ],
}
