name: Test Go

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test-go.yml"
      - "go.mod"
      - "backend/**"

  pull_request:
    paths:
      - ".github/workflows/test-go.yml"
      - "go.mod"
      - "backend/**"
    branches-ignore:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go test -p 1 ./backend/...
